// ============================================
// BRAIN/DOCUMENTS/PDF — HANDLERS
// All return data only. No sock, no sending.
// ============================================

import { makePdf, imgToPdf, mergePdfs, getPdfInfo, makeCertificate, qrToPdf } from './pdf.js';

export async function makePdfHandler(text) {
    if (!text || !text.trim()) throw new Error('No text provided.');
    const buffer = await makePdf(text.trim());
    return { buffer, filename: 'document.pdf' };
}

export async function imgToPdfHandler(imageBuffer, mimeType) {
    if (!imageBuffer) throw new Error('No image provided.');
    const buffer = await imgToPdf(imageBuffer, mimeType || 'image/jpeg');
    return { buffer, filename: 'image.pdf' };
}

export async function mergePdfsHandler(pdfBuffers) {
    if (!pdfBuffers || pdfBuffers.length < 2) throw new Error('Send at least 2 PDF files.');
    const buffer = await mergePdfs(pdfBuffers);
    return { buffer, count: pdfBuffers.length, filename: 'merged.pdf' };
}

export async function pdfInfoHandler(pdfBuffer) {
    if (!pdfBuffer) throw new Error('No PDF provided.');
    const info = await getPdfInfo(pdfBuffer);
    return info;
}

export async function certificateHandler(name) {
    if (!name || !name.trim()) throw new Error('Provide a name for the certificate.');
    const buffer = await makeCertificate(name.trim());
    return { buffer, name: name.trim(), filename: `certificate_${name.trim().replace(/\s+/g, '_')}.pdf` };
}

export async function invoiceHandler(data) {
    // data: { client, invoiceNo, items: [{desc, amount}] }
    if (!data.client || !data.items?.length) throw new Error('Provide client name and at least one item.');
    const { PDFDocument, StandardFonts, rgb } = await import('pdf-lib');

    const pdfDoc = await PDFDocument.create();
    const page   = pdfDoc.addPage([595, 842]);
    const { width, height } = page.getSize();

    const fontBold   = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const fontNormal = await pdfDoc.embedFont(StandardFonts.Helvetica);

    const date      = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    const invoiceNo = data.invoiceNo || `INV-${Date.now().toString().slice(-6)}`;
    const total     = data.items.reduce((s, i) => s + i.amount, 0);

    // header
    page.drawText('INVOICE', { x: 50, y: height - 70, size: 36, font: fontBold, color: rgb(0.1, 0.1, 0.5) });
    page.drawText(`#${invoiceNo}`, { x: 50, y: height - 100, size: 14, font: fontNormal, color: rgb(0.4, 0.4, 0.4) });
    page.drawText(`Date: ${date}`, { x: width - 200, y: height - 70, size: 12, font: fontNormal, color: rgb(0.3, 0.3, 0.3) });

    // divider
    page.drawLine({ start: { x: 50, y: height - 120 }, end: { x: width - 50, y: height - 120 }, thickness: 1, color: rgb(0.7, 0.7, 0.7) });

    // bill to
    page.drawText('Bill To:', { x: 50, y: height - 150, size: 12, font: fontBold, color: rgb(0.3, 0.3, 0.3) });
    page.drawText(data.client, { x: 50, y: height - 170, size: 14, font: fontBold, color: rgb(0, 0, 0) });

    // items header
    page.drawText('Description', { x: 50,         y: height - 230, size: 12, font: fontBold, color: rgb(0.2, 0.2, 0.2) });
    page.drawText('Amount',      { x: width - 120, y: height - 230, size: 12, font: fontBold, color: rgb(0.2, 0.2, 0.2) });
    page.drawLine({ start: { x: 50, y: height - 240 }, end: { x: width - 50, y: height - 240 }, thickness: 0.5, color: rgb(0.8, 0.8, 0.8) });

    // items
    let y = height - 265;
    for (const item of data.items) {
        page.drawText(item.desc,                    { x: 50,         y, size: 12, font: fontNormal, color: rgb(0.1, 0.1, 0.1) });
        page.drawText(`$${item.amount.toFixed(2)}`, { x: width - 120, y, size: 12, font: fontNormal, color: rgb(0.1, 0.1, 0.1) });
        y -= 25;
    }

    // total
    page.drawLine({ start: { x: 50, y: y - 5 }, end: { x: width - 50, y: y - 5 }, thickness: 1, color: rgb(0.5, 0.5, 0.5) });
    page.drawText('TOTAL',              { x: 50,         y: y - 30, size: 14, font: fontBold, color: rgb(0, 0, 0) });
    page.drawText(`$${total.toFixed(2)}`, { x: width - 120, y: y - 30, size: 14, font: fontBold, color: rgb(0.1, 0.1, 0.5) });

    // footer
    page.drawText('Generated by Eren Bot • Ernest Tech House', { x: 50, y: 40, size: 10, font: fontNormal, color: rgb(0.7, 0.7, 0.7) });

    const buffer = Buffer.from(await pdfDoc.save());
    return { buffer, client: data.client, invoiceNo, items: data.items, total, date, filename: `invoice_${invoiceNo}.pdf` };
}

export async function qrToPdfHandler(text) {
    if (!text || !text.trim()) throw new Error('Provide text or URL for the QR code.');
    const buffer = await qrToPdf(text.trim());
    return { buffer, text: text.trim(), filename: 'qrcode.pdf' };
}